ALTER TABLE hotspots
  ADD COLUMN IF NOT EXISTS radius_tl integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS radius_tr integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS radius_br integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS radius_bl integer NOT NULL DEFAULT 0;
